INSERT INTO clientes (nombre, ciudad) VALUES
('Juan Pérez', 'Santiago'),
('María González', 'Valparaíso'),
('Pedro Muñoz', 'Concepción'),
('Ana Rojas', 'La Serena'),
('Carlos Soto', 'Antofagasta'),
('Fernanda Silva', 'Temuco'),
('Luis Herrera', 'Rancagua'),
('Camila Torres', 'Talca'),
('Jorge Ramírez', 'Iquique'),
('Paula Martínez', 'Arica'),
('Diego Fuentes', 'Puerto Montt'),
('Valentina López', 'Osorno'),
('Francisco Molina', 'Chillán'),
('Daniela Reyes', 'Curicó'),
('Ricardo Vega', 'Calama'),
('Natalia Campos', 'Copiapó'),
('Sebastián Navarro', 'San Fernando'),
('Constanza Pizarro', 'Ovalle'),
('Matías Contreras', 'Quilpué'),
('Andrea Bustos', 'Villa Alemana'),
('Cristóbal Núñez', 'Punta Arenas'),
('Macarena Figueroa', 'Coyhaique'),
('Ignacio Salinas', 'Los Ángeles'),
('Karla Araya', 'Linares'),
('Felipe Espinoza', 'Melipilla'),
('Paulina Godoy', 'San Antonio'),
('Héctor Valdés', 'La Calera'),
('Javiera Cáceres', 'Peñaflor'),
('Rodrigo Palma', 'Buin'),
('Carolina Méndez', 'Machalí');
